type Image {
  width: Int
  height: Int
  url: String
}

# type StandardResolution {
#   width: Int
#   height: Int
#   url: String
# }

# type LowResolution {
#   width: Int
#   height: Int
#   url: String
# }

# type Thumbnail {
#   width: Int
#   height: Int
#   url: String
# }

type Images {
  standard_resolution: Image!
  low_resolution: Image!
  thumbnail: Image!
}

# Types with identical fields:
# StandardResolution LowResolution Thumbnail

type Post {
  instagram_id: String!
  caption: String!
  link: String!
  images: Images!
}

# type User {
#   id: ID! @unique
#   age: Int
#   email: String! @unique
#   name: String!
#   posts: [Post!]!
# }

type Query {
  allPosts: [Post!]
  allImages: [Image!]
#   todosByCompletedFlag(completed: Boolean!): [Todo!]
}


# {id: "2144811289880636561_20196334360", link: "https://www.instagram.com/p/B3D5oEjlSyR/", images: {thumbnail: {width: 150, height: 150, url: "https://scontent.cdninstagram.com/vp/d19b67ab6c6a6…5031253506_n.jpg?_nc_ht=scontent.cdninstagram.com"}, low_resolution: {width: 320, height: 211, url: "https://scontent.cdninstagram.com/vp/be916f7de4407…5031253506_n.jpg?_nc_ht=scontent.cdninstagram.com"}, standard_resolution: {width: 640, height: 423, url: "https://scontent.cdninstagram.com/vp/be7f720fa62ac…5031253506_n.jpg?_nc_ht=scontent.cdninstagram.com"}}, caption: "X."}

